export const UPDATE_ARTWORK_ARRAY = "UPDATE_ARTWORK_ARRAY";
export const SELECT_ARTWORK = "SELECT_ARTWORK";
export const SELECT_ANNOTATION = "SELECT_ANNOTATION";
export const LOGIN_USER = "LOGIN_USER";
